["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
main = [
  "src/identicon.cairo",
]
bpm = [
  "src/bpm.cairo"
]
